// Code generated by entc, DO NOT EDIT.

package ent

import (
	"backend/database/ent/schema"
	"backend/database/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescProfilePicture is the schema descriptor for profile_picture field.
	userDescProfilePicture := userFields[3].Descriptor()
	// user.DefaultProfilePicture holds the default value on creation for the profile_picture field.
	user.DefaultProfilePicture = userDescProfilePicture.Default.(string)
	// user.ProfilePictureValidator is a validator for the "profile_picture" field. It is called by the builders before save.
	user.ProfilePictureValidator = userDescProfilePicture.Validators[0].(func(string) error)
}
